In [20]:
import pandas as pd
import numpy as np
from pyvalet import ValetInterpreter
import datetime as dt
vi = ValetInterpreter()

In [70]:

# start_date=2013-05-09 & end_date=2020-07-12,
# GoC Bond Purchase program
df = vi.get_group_observations("GBPP", response_format='csv')
df.tail()

#GoC mortgage bonds
df1 = vi.get_group_observations("CANADA_MORTGAGE_BOND", response_format='csv')
df1.tail()

#GoC provincial bonds compared to corporate bonds and GoC bonds
df2 = vi.get_group_observations("SAN_BEDP20180709_C1", response_format='csv')
df2

#Canada overnight repo rate average
df3 = vi.get_group_observations("CORRA_GRAPH", response_format='csv')
df3.set_index("date")

         \ndate"  AVG.INTWO  CORRA_TRIMMED_VOLUME
0     1997-08-12     3.2500                   NaN
1     1997-08-18     3.3000                   NaN
2     1997-08-19     3.2600                   NaN
3     1997-08-20     3.3450                   NaN
4     1997-08-21     3.3850                   NaN
5     1997-08-22     3.2650                   NaN
6     1997-08-25     3.3360                   NaN
7     1997-08-26     3.2670                   NaN
8     1997-08-27     3.3070                   NaN
9     1997-08-28     3.4615                   NaN
10    1997-09-02     3.4426                   NaN
11    1997-09-03     3.2820                   NaN
12    1997-09-04     3.3477                   NaN
13    1997-09-05     3.2500                   NaN
14    1997-09-08     3.2702                   NaN
15    1997-09-09     3.2890                   NaN
16    1997-09-10     3.2730                   NaN
17    1997-09-11     3.3400                   NaN
18    1997-09-12     3.2769                   NaN
19    1997-09-15     3.4569                   NaN
20    1997-09-16     3.2430                   NaN
21    1997-09-17     3.2392                   NaN
22    1997-09-18     3.3599                   NaN
23    1997-09-19     3.2348                   NaN
24    1997-09-22     3.2395                   NaN
25    1997-09-23     3.2664                   NaN
26    1997-09-24     3.2680                   NaN
27    1997-09-25     3.3013                   NaN
28    1997-09-26     3.3009                   NaN
29    1997-09-29     3.3785                   NaN
...          ...        ...                   ...
5708  2020-06-10     0.2289                   NaN
5709  2020-06-11     0.2218                   NaN
5710  2020-06-12     0.2400          9.680106e+09
5711  2020-06-15     0.2200          8.273722e+09
5712  2020-06-16     0.2300          7.944744e+09
5713  2020-06-17     0.2400          8.852311e+09
5714  2020-06-18     0.2300          9.465863e+09
5715  2020-06-19     0.2500          1.044414e+10
5716  2020-06-22     0.2500          9.138804e+09
5717  2020-06-23     0.2500          7.236518e+09
5718  2020-06-24     0.2500          4.146223e+09
5719  2020-06-25     0.2500          6.488281e+09
5720  2020-06-26     0.2500          9.210482e+09
5721  2020-06-29     0.2500          8.925998e+09
5722  2020-06-30     0.2500          1.101677e+10
5723  2020-07-02     0.2500          7.475702e+09
5724  2020-07-03     0.2200          7.580805e+09
5725  2020-07-06     0.2200          7.050087e+09
5726  2020-07-07     0.2500          7.449705e+09
5727  2020-07-08     0.2500          7.325307e+09
5728  2020-07-09     0.2500          7.879175e+09
5729  2020-07-10     0.2500          7.859680e+09
5730  2020-07-13     0.2300          8.421206e+09
5731  2020-07-14     0.2500          8.992945e+09
5732  2020-07-15     0.2500          7.489787e+09
5733  2020-07-16     0.2500          8.990802e+09
5734  2020-07-17     0.2500          1.029423e+10
5735  2020-07-20     0.2500          9.664377e+09
5736  2020-07-21     0.2500          1.069547e+10
5737  2020-07-22     0.2500          1.098328e+10

[5738 rows x 3 columns]

In [65]:
gbpp_df = df[["GBPP_AUCTION_DATE", "GBPP_TOTAL_AMOUNT_PURCHASED"]]
gbpp_df["GBPP_AUCTION_DATE"] = pd.to_datetime(gbpp_df["GBPP_AUCTION_DATE"])
gbpp_df1 = gbpp_df.set_index("GBPP_AUCTION_DATE")
gbpp_df1.tail()

corra_graph = df3.hvplot.line()

C:\Users\nites\anaconda3\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

AttributeError: 'DataFrame' object has no attribute 'hvplot'

In [40]:
gbpp_df1.drop(level=1).dropna(inplace=True)
gbpp_df1.head()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'